-- CREATE CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  product_count INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- CREATE PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC NOT NULL,
  mrp NUMERIC,
  image_url TEXT,
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  category_name TEXT,
  stock INT DEFAULT 0,
  material TEXT,
  size TEXT,
  featured BOOLEAN DEFAULT FALSE,
  is_visible BOOLEAN DEFAULT TRUE,
  is_new_arrival BOOLEAN DEFAULT FALSE,
  additional_category_ids JSONB DEFAULT '[]'::jsonb,
  additional_category_names TEXT[] DEFAULT '{}'::text[],
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) optionally, or disable it for simplicity.
-- Since this is an administrative dashboard and public store app:
-- If you want anyone to read, you can enable read access policy.
-- For simplicity, let's write policy commands to make reading public:

ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on categories" 
ON categories FOR SELECT 
USING (true);

CREATE POLICY "Allow public read access on products" 
ON products FOR SELECT 
USING (true);

CREATE POLICY "Allow all actions on categories for authenticated / anon" 
ON categories FOR ALL 
USING (true)
WITH CHECK (true);

CREATE POLICY "Allow all actions on products for authenticated / anon" 
ON products FOR ALL 
USING (true)
WITH CHECK (true);

-- Functions to increment/decrement category counts via API RPC
CREATE OR REPLACE FUNCTION increment_category_count(row_id BIGINT)
RETURNS VOID AS $$
BEGIN
  UPDATE categories
  SET product_count = COALESCE(product_count, 0) + 1
  WHERE id = row_id;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION decrement_category_count(row_id BIGINT)
RETURNS VOID AS $$
BEGIN
  UPDATE categories
  SET product_count = GREATEST(0, COALESCE(product_count, 0) - 1)
  WHERE id = row_id;
END;
$$ LANGUAGE plpgsql;

-- Migration script for existing databases:
ALTER TABLE products ADD COLUMN IF NOT EXISTS additional_category_ids JSONB DEFAULT '[]'::jsonb;
ALTER TABLE products ADD COLUMN IF NOT EXISTS additional_category_names TEXT[] DEFAULT '{}'::text[];


